# Generated by Django 3.1.7 on 2021-03-05 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210305_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 5, 22, 26, 3, 385991)),
        ),
    ]
