# Generated by Django 3.1.7 on 2021-03-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210305_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.list'),
            preserve_default=False,
        ),
    ]
