# Generated by Django 3.1.7 on 2021-02-24 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210221_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 12, 44, 39, 708397)),
        ),
    ]
