# Generated by Django 3.1.7 on 2021-02-26 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210224_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('creation_date', models.DateField(default=datetime.datetime(2021, 2, 26, 21, 8, 16, 954374))),
                ('due_on_date', models.DateField()),
                ('owner', models.CharField(default='owner', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
