# Generated by Django 3.1.7 on 2021-02-26 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210226_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 26, 15, 41, 9, 330235, tzinfo=utc)),
        ),
    ]
