# Generated by Django 3.1.7 on 2021-02-26 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20210226_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 26, 21, 42, 54, 249214)),
        ),
    ]
