# Generated by Django 3.1.7 on 2021-02-27 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20210226_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 8, 55, 0, 800351)),
        ),
    ]
